Repository heereal/Bunyang_MoeumZip, pull requests merged in 2023-02, with the labels that each got.

#11 [edit] Header 수정 및 Main Page 컴포넌트 분리
  src/components/GlobalComponents/AlertUI/AlertUI.tsx
  src/components/GlobalComponents/AlertUI/style.tsx
  src/components/GlobalComponents/CategoryBar/CategoryBar.tsx
  src/components/GlobalComponents/CategoryBar/style.tsx
  src/components/GlobalComponents/Header/Header.tsx
  src/components/GlobalComponents/Header/style.tsx
  src/components/GlobalComponents/Layout/Layout.tsx
  src/components/GlobalComponents/TopBtn/TopBtn.tsx
  src/components/GlobalComponents/TopBtn/style.tsx
  src/components/MainPage/CountTabs/CountTabs.tsx
  src/components/MainPage/CountTabs/style.tsx
  src/components/MainPage/HomeList/HomeList.tsx
  src/pages/index.tsx
Labels: enhancement

#12 [feat] 회원가입 기능 구현
  src/common/categoryList.ts
  src/components/GlobalComponents/LoginModal/LoginModal.tsx
  src/pages/loading/index.tsx
  src/pages/signup/index.tsx
  src/styles/globals.css
  src/styles/signup.style.tsx
Labels: enhancement

#21 [feat] calendar 페이지에 SSG 적용
  src/assets/spinner.gif
  src/components/GlobalComponents/Header/Header.tsx
  src/components/GlobalComponents/LoginModal/LoginModal.tsx
  src/components/GlobalComponents/LoginModal/style.tsx
  src/pages/calendar/index.tsx
  src/pages/loading/index.tsx
  src/pages/my/index.tsx
  src/pages/signup/index.tsx
  types/type.d.ts
Labels: enhancement

#20 [feat] 어드민페이지 좌표메이커 기능 구현
  public/dummy.json
  src/common/api.ts
  src/components/DetailPage/Comments/AddComment.tsx
  src/components/DetailPage/Comments/CommentsList.tsx
  src/components/DetailPage/Comments/EditComment.tsx
  src/components/DetailPage/PostDetail/PostDetail.tsx
  src/components/GlobalComponents/Header/Header.tsx
  src/components/GlobalComponents/MapSection/MapSection.tsx
  src/components/MainPage/HomeList/HomeList.tsx
  src/pages/_app.tsx
  src/pages/admin/nemo042116.tsx
  src/pages/calendar/index.tsx
  src/pages/detail/[postid].tsx
  src/store/selectors.ts
  types/type.d.ts
Labels: enhancement

#19 [feat] Main Page 카테고리별 리스트 조회 구현
  src/common/categoryList.ts
  src/components/GlobalComponents/CategoryBar/CategoryBar.tsx
  src/components/GlobalComponents/CategoryBar/style.tsx
  src/components/GlobalComponents/Layout/Layout.tsx
  src/components/GlobalComponents/Search/Search.tsx
  src/components/MainPage/CountTabs/CountTabs.tsx
  src/components/MainPage/HomeList/HomeList.tsx
  src/components/SearchPage/SearchResults.tsx
  src/hooks/useMap.ts
  src/pages/_app.tsx
  src/pages/admin/index.tsx
  src/pages/admin/nemo042116.tsx
  src/pages/index.tsx
  src/pages/my/index.tsx
  src/pages/search/[keyword].tsx
  src/pages/signup/index.tsx
  src/store/selectors.ts
  src/styles/signup.style.tsx
  types/type.d.ts
Labels: enhancement

#22 [feat] 청약경쟁률 /당첨자 확인 버튼 구현
  src/components/GlobalComponents/CategoryBar/CategoryBar.tsx
  src/components/GlobalComponents/CategoryBar/style.tsx
  src/components/GlobalComponents/InfoLink/InfoLink.tsx
  src/components/GlobalComponents/InfoLink/style.tsx
Labels: enhancement

#23 [feat] Main Page 전체 리스트 추가 및 API 데이터 재가공
  src/components/GlobalComponents/HomeList/HomeList.tsx
  src/components/GlobalComponents/HomeList/style.tsx
  src/components/MainPage/CountTabs.tsx
  src/components/MainPage/HomeList/style.tsx
  src/components/MainPage/style.tsx
  src/components/SearchPage/SearchResults.tsx
  src/pages/admin/nemo042116.tsx
  src/pages/index.tsx
  src/pages/search/[keyword].tsx
  src/styles/search.style.tsx
  types/type.d.ts
Labels: enhancement

#25 [feat] 북마크 기능 및 마이페이지에 내가 북마크한 목록 불러오기 구현
  next.config.js
  src/common/api.ts
  src/components/DetailPage/PostDetail/PostDetail.tsx
  src/components/GlobalComponents/LoadingSpinner/LoadingSpinner.tsx
  src/hooks/index.ts
  src/hooks/useBookmark.tsx
  src/pages/loading/index.tsx
  src/pages/my/index.tsx
Labels: enhancement

#26 [feat] Admin page API call 버튼 추가 및 css 수정
  src/assets/apiCallButton.jpg
  src/assets/apiCallButton_blue.png
  src/assets/apiCallButton_green.png
  src/assets/apiCallButton_red.png
  src/components/GlobalComponents/AlertUI/AlertUI.tsx
  src/components/GlobalComponents/AlertUI/style.tsx
  src/components/GlobalComponents/Layout/Layout.tsx
  src/components/GlobalComponents/MapSection/MapSection.tsx
  src/components/GlobalComponents/Search/Search.tsx
  src/pages/admin/nemo042116.tsx
  src/pages/index.tsx
  src/pages/search/[keyword].tsx
  src/styles/admin.style.tsx
Labels: enhancement

#28 [edit] 카테고리 선택 리스트 수정
  src/components/DetailPage/Comments/AddComment.tsx
  src/components/DetailPage/Comments/EditComment.tsx
  src/components/GlobalComponents/Search/Search.tsx
  src/components/MainPage/CountTabs.tsx
  src/hooks/useBookmark.tsx
  src/pages/admin/nemo042116.tsx
  src/pages/my/index.tsx
  src/pages/signup/index.tsx
Labels: enhancement

#34 [design] 로그인모달, 회원가입 페이지, 마이 페이지 UI 구현
  src/assets/transparentProfile.png
  src/common/categoryList.ts
  src/common/firebase.ts
  src/components/GlobalComponents/Header/Header.tsx
  src/components/GlobalComponents/Header/style.tsx
  src/components/GlobalComponents/HomeList/HomeList.tsx
  src/components/GlobalComponents/HomeList/style.tsx
  src/components/GlobalComponents/InfoLink/InfoLink.tsx
  src/components/GlobalComponents/InfoLink/style.tsx
  src/components/GlobalComponents/Layout/Layout.tsx
  src/components/GlobalComponents/LoginModal/LoginModal.tsx
  src/components/GlobalComponents/LoginModal/style.tsx
  src/components/GlobalComponents/SearchInput/SearchInput.tsx
  src/components/GlobalComponents/SearchInput/style.tsx
  src/components/GlobalComponents/SelectMyRegion/SelectMyRegion.tsx
  src/components/GlobalComponents/SelectMyRegion/style.tsx
  src/components/GlobalComponents/SelectMyTypes/SelectMyTypes.tsx
  src/components/MainPage/CategoryBar/CategoryBar.tsx
  src/components/MainPage/CategoryBar/style.tsx
  src/components/MainPage/CountTabs/CountTabs.tsx
  src/components/MainPage/CountTabs/style.tsx
  src/components/MainPage/style.tsx
  src/components/MyPage/EditProfile/EditProfile.tsx
  src/components/MyPage/EditProfile/style.tsx
  src/components/MyPage/MyTabs/MyTabs.tsx
  src/components/MyPage/MyTabs/style.tsx
  src/hooks/useBookmark.tsx
  src/pages/_app.tsx
  src/pages/api/auth/[...nextauth].ts
  src/pages/api/hello.ts
  src/pages/index.tsx
  src/pages/my/index.tsx
  src/pages/signup/index.tsx
  src/store/selectors.ts
  src/styles/globals.css
  src/styles/my.style.tsx
  src/styles/search.style.tsx
  src/styles/signup.style.tsx
  types/type.d.ts
Labels: CSS

#35 [design] 상세페이지 CSS 구현
  src/common/api.ts
  src/common/firebase.ts
  src/common/utils.ts
  src/components/DetailPage/Comments/AddComment.tsx
  src/components/DetailPage/Comments/CommentsList.tsx
  src/components/DetailPage/Comments/EditComment.tsx
  src/components/DetailPage/Comments/style.tsx
  src/components/DetailPage/PostDetail/PostDetail.tsx
  src/components/DetailPage/PostDetail/style.tsx
  src/components/GlobalComponents/MapSection/MapSection.tsx
  src/pages/admin/nemo042116.tsx
  src/styles/detail.style.tsx
  src/styles/globals.css
  types/type.d.ts
Labels: CSS

#33 [design]Main, Search UI 1차 구현
  src/common/utils.ts
  src/components/GlobalComponents/Header/Header.tsx
  src/components/GlobalComponents/Header/style.tsx
  src/components/GlobalComponents/HomeList/HomeList.tsx
  src/components/GlobalComponents/HomeList/style.tsx
  src/components/GlobalComponents/InfoLink/style.tsx
  src/components/GlobalComponents/SearchInput/style.tsx
  src/components/MainPage/CategoryBar/CategoryBar.tsx
  src/components/MainPage/CategoryBar/style.tsx
  src/components/MainPage/CountTabs/CountTabs.tsx
  src/components/MainPage/CountTabs/style.tsx
  src/pages/admin/nemo042116.tsx
  src/pages/index.tsx
  src/pages/search/[keyword].tsx
  src/styles/search.style.tsx
Labels: enhancement, CSS

#37 [design] 화면 크기에 따라 필터 위치 바뀌는 것 수정
  src/components/GlobalComponents/Header/style.tsx
  src/components/GlobalComponents/SearchInput/style.tsx
  src/components/MainPage/CategoryBar/style.tsx
Labels: CSS

#39 [feat] 지도 에러 해결 ,오버레이 적용
  src/components/DetailPage/Comments/CommentsList.tsx
  src/components/DetailPage/PostDetail/PostDetail.tsx
  src/components/DetailPage/PostDetail/style.tsx
  src/components/GlobalComponents/HeadTitle/HeadTitle.tsx
  src/components/GlobalComponents/MapSection/MapSection.tsx
  src/components/GlobalComponents/MapSection/Overlay.tsx
  src/components/GlobalComponents/MapSection/style.tsx
  src/components/GlobalComponents/SearchInput/SearchInput.tsx
  src/components/MyPage/EditProfile/EditProfile.tsx
  src/pages/calendar/index.tsx
  src/pages/index.tsx
  src/pages/my/index.tsx
  src/pages/search/[keyword].tsx
  src/pages/signup/index.tsx
Labels: enhancement

#40 [feat] 마이페이지 프로필 수정 기능 구현 및 리팩토링
  src/components/GlobalComponents/Header/Header.tsx
  src/components/GlobalComponents/LoginModal/LoginModal.tsx
  src/components/GlobalComponents/LoginModal/style.tsx
  src/components/MyPage/EditProfile/EditProfile.tsx
  src/components/MyPage/EditProfile/style.tsx
  src/components/MyPage/EditProfileModal/EditProfileModal.tsx
  src/components/MyPage/EditProfileModal/style.tsx
  src/components/MyPage/MyTabs/MyTabs.tsx
  src/components/MyPage/MyTabs/style.tsx
  src/pages/calendar/index.tsx
  src/pages/loading/index.tsx
  src/pages/my/index.tsx
  src/store/selectors.ts
  src/styles/claendar.style.tsx
Labels: enhancement

#41 [feat] Custom Alert 및 confrim 적용
  src/assets/NoResult.png
  src/common/utils.ts
  src/components/DetailPage/Comments/AddComment.tsx
  src/components/DetailPage/Comments/EditComment.tsx
  src/components/GlobalComponents/Header/Header.tsx
  src/components/GlobalComponents/Header/style.tsx
  src/components/GlobalComponents/HomeList/HomeList.tsx
  src/components/GlobalComponents/HomeList/style.tsx
  src/components/GlobalComponents/NoResult/NoResult.tsx
  src/components/GlobalComponents/NoResult/style.tsx
  src/components/GlobalComponents/SearchInput/SearchInput.tsx
  src/components/GlobalComponents/SearchInput/style.tsx
  src/components/MainPage/CategoryBar/CategoryBar.tsx
  src/components/MainPage/CategoryBar/style.tsx
  src/components/MainPage/CountTabs/CountTabs.tsx
  src/components/MainPage/CountTabs/style.tsx
  src/components/MainPage/InfoLink/InfoLink.tsx
  src/components/MainPage/InfoLink/style.tsx
  src/components/MyPage/EditProfile/EditProfile.tsx
  src/components/MyPage/EditProfileModal/EditProfileModal.tsx
  src/components/MyPage/MyTabs/MyTabs.tsx
  src/hooks/useBookmark.tsx
  src/pages/admin/nemo042116.tsx
  src/pages/search/[keyword].tsx
  src/pages/signup/index.tsx
  src/styles/search.style.tsx
  types/type.d.ts
Labels: enhancement

#47 [docs] README.md 업데이트
  README.md
  src/components/DetailPage/PostDetail/style.tsx
  src/components/GlobalComponents/Header/Header.tsx
Labels: documentation

#50 [fix] SSR error 해결
  README.md
  src/components/DetailPage/PostDetail/style.tsx
  src/components/GlobalComponents/Header/Header.tsx
  src/components/GlobalComponents/MapSection/MapSection.tsx
  src/components/MainPage/CategoryBar/CategoryBar.tsx
  src/components/MainPage/CountTabs/CountTabs.tsx
  src/pages/admin/nemo042116.tsx
  src/pages/index.tsx
  src/store/selectors.ts
Labels: Fix

#53 [fix] 마이페이지에서 관심 카테고리 설정이 바로 업데이트되지 않는 문제 해결
  src/components/GlobalComponents/Header/Header.tsx
  src/components/GlobalComponents/Header/style.tsx
  src/components/MyPage/MyTabs/MyTabs.tsx
  src/pages/admin/nemo042116.tsx
  src/pages/my/index.tsx
  src/styles/globals.css
Labels: Fix

#51 [feat] 지역별 분양형태 필터링 구현 [edit] MainPage 리스트 카드 수정
  src/common/categoryList.ts
  src/components/GlobalComponents/HeadTitle/HeadTitle.tsx
  src/components/GlobalComponents/HomeList/HomeList.tsx
  src/components/GlobalComponents/NoResult/NoResult.tsx
  src/components/MainPage/CategoryBar/CategoryBar.tsx
  src/components/MainPage/CountTabs/CountTabs.tsx
  src/hooks/useHomeList.ts
  src/hooks/useTabList.ts
  src/pages/admin/nemo042116.tsx
  src/pages/calendar/index.tsx
  src/pages/detail/[postid].tsx
  src/pages/index.tsx
  src/pages/my/index.tsx
  src/pages/search/[keyword].tsx
  src/pages/signup/index.tsx
  src/store/selectors.ts
Labels: enhancement

#52 [feat] 관리자 페이지 DB 업데이트 로직 수정
  src/pages/admin/nemo042116.tsx
  src/styles/globals.css
Labels: enhancement
